### PR TITLE
Fix #1064: ValidatorCommand fails when target file name contains a space

### LINKED ISSUE #1064: ValidatorCommand fails when target file name contains a space
```
c:\Code\sarif-sdk\bld\bin\AnyCPU_Release\Sarif.Multitool\net461>Sarif.Multitool.exe validate --json-schema c:\Code\sarif-sdk\src\Sarif\Schemata\Sarif.schema.json --output "c:\Users\Larry Golding\Desktop\SarifSdk.validation.sarif" "C:\Users\Larry Golding\OneDrive\Documents\SARIF\Semmle\SarifSdk\SarifSdk.sarif
Analyzing...
error ERR999.UnhandledEngineException : An exception was raised during analysis. (Could not find a part of the path 'C:\Users\Larry%20Golding\OneDrive\Documents\SARIF\Semmle\SarifSdk\SarifSdk.sarif'.)
```

### PR DESCRIPTION
**Pull request by lgolding**
The symptom of the bug is:
```
error ERR999.UnhandledEngineException : An exception was raised during analysis. (Could not find a 
part of the path 'C:\Users\Larry%20Golding\OneDrive\Documents\SARIF\Semmle\SarifSdk\SarifSdk.sarif'.)
```
Note the `%20` instead of a space in the file name. This is because the code is using `Uri.AbsolutePath` in a place it should be using `Uri.OriginalString`.

This should have been a simple one-line fix. Unfortunately, neither the top level of Sarif.Multitool nor the SARIF driver command infrastructure was unit testable. There wasn't even a unit test project for Sarif.Multitool. We took the opportunity to create the unit test project, inject a mockable file system into the command infrastructure, and write a single unit test to regress this issue. (The test fails without the fix, and passes with the fix.)

No doubt there are other places where Sarif.Multitool accesses the file system or other resources directly, but with the infrastructure in place, it should be straightforward to inject the necessary dependencies where needed.

### CODE REVIEW

File: src/Sarif.Multitool/ValidateCommand.cs [hunk 1]
```diff
@@ -59,7 +62,7 @@ protected override SarifValidationContext CreateContext(ValidateOptions options,
                 // Deserialize will return null if there are any JSON deserialization errors
                 // (which can happen, for example, if a property required by the schema is
                 // missing. In that case, again, there's no point in going on.
-                context.InputLogContents = File.ReadAllText(context.TargetUri.AbsolutePath);
+                context.InputLogContents = FileSystem.ReadAllText(context.TargetUri.OriginalString);
```
Comment (lgolding) [inline src/Sarif.Multitool/ValidateCommand.cs]: >OriginalString [](start = 84, length = 14)

The one-line fix: `AbsolutePath` => `OriginalString`.

**Comment by lgolding** [comment]
@michaelcfanning is added to the review. #Closed

**Comment by lgolding** [comment]
@EasyRhinoMSFT is added to the review. #Closed

**Comment by lgolding** [comment]
@easyrhino is added to the review. #Closed

**Comment by lgolding** [comment]
@cfaucon is added to the review. #Closed

**Comment by lgolding** [comment]
@rtaket is added to the review. #Closed

**Comment by lgolding** [comment]
@Evmaus-MS is added to the review. #Closed

File: src/Sarif.UnitTests/JsonTests.cs [hunk 2]
```diff
@@ -12,14 +12,6 @@ namespace Microsoft.CodeAnalysis.Sarif
 {
     public abstract class JsonTests
     {
-        private const SarifVersion CurrentVersion = SarifVersion.TwoZeroZero;
-
-        protected static readonly string SarifSchemaUri =
-            SarifUtilities.ConvertToSchemaUri(CurrentVersion).OriginalString;
-
-        protected static readonly string SarifFormatVersion =
-            SarifUtilities.ConvertToText(CurrentVersion);
```
Comment (lgolding) [inline src/Sarif.UnitTests/JsonTests.cs]: >; [](start = 56, length = 1)

Moved these lines to `SarifUtilities` so I could use them in the Multitool unit tests as well as the Sarif unit tests. I could have moved them to test utilities, but really they don't seem test-specific to me; they seem useful in product code.
