### PR TITLE
Fix #1791: ESLint formatter returns invalid SARIF in some cases

### LINKED ISSUE #1791: ESLint formatter returns invalid SARIF in some cases
Specifically, we do not always provide the rule ID, e.g.,

~~~
{
  "level": "error",
  "message": {
    "text": "Parsing error: ImportDeclaration should appear when the mode is ES6 and in the module context."
  },
  "locations": [
    {
      "physicalLocation": {
        "artifactLocation": {
          "uri": "file:///C:/Dev/SecureApp/SecureApp/ts/node_modules/esrecurse/gulpfile.babel.js",
          "index": 905
        }
      }
    }
  ]
},
~~~

### PR DESCRIPTION
**Pull request by lgolding**
At times, ESLint emits a message with no `ruleId`, indicating an internal error in ESLint. Represent this in SARIF as a `toolExecutionNotification` with `level: "error"`, rather than as a `result` with no `ruleId`, which is invalid.

This affects some unit tests, which now must always provide a `ruleId`.

Also:
- Per the spec, emit `run.results` even if the array is empty, as a positive indicator that the tool found no results. This affects the unit test which previously expected `run.results` to be `undefined` in this case.

### CODE REVIEW

**Comment by lgolding** [comment]
@michaelcfanning is added to the review. #Closed

**Comment by lgolding** [comment]
@boAndron is added to the review. #Closed

File: src/ESLint.Formatter/sarif.js [hunk 1]
```diff
@@ -54,13 +54,20 @@ module.exports = function (results, data) {
 
     const sarifFiles = {};
     const sarifArtifactIndices = {};
-    var nextArtifactIndex = 0;
+    let nextArtifactIndex = 0;
```
Comment (lgolding) [inline src/ESLint.Formatter/sarif.js]: >let [](start = 4, length = 3)

`let` is preferable because its block scoping behavior is more understandable to most people than `var`'s function body scoping.

File: src/ESLint.Formatter/sarif.js [hunk 2]
```diff
@@ -145,12 +152,29 @@ module.exports = function (results, data) {
...
-                            sarifResult.ruleIndex = sarifRuleIndices[message.ruleId];
+                            sarifRepresentation.ruleIndex = sarifRuleIndices[message.ruleId];
+                        }
+                    } else {
+                        // ESLint produces a message with no ruleId when it encounters an internal
+                        // error. SARIF represents this as a tool execution notification rather
+                        // than as a result, and a notification has a descriptor.id property rather
+                        // than a ruleId property.
+                        sarifRepresentation.descriptor = {
+                            id: internalErrorId
```
Comment (michaelcfanning) [inline src/ESLint.Formatter/sarif.js]: >internalErrorId [](start = 32, length = 15)

What kind of internal errors are we talking about? If the internal error is something like: you passed us code to analyze that isn't syntactically correct, that would be a user configuration error, not an internal error. Some tools seem to mix these concepts together. A tool notification error is intended to convey 'we should have been able to scan for you, but an issue in the engine itself prevented us from succeeding'. A configuration error is 'we received inputs or configuration by the user which prevented us from completing a scan'.

File: src/ESLint.Formatter/sarif.js [hunk 3]
```diff
@@ -178,8 +207,17 @@ module.exports = function (results, data) {
         });
     }
 
-    if (sarifResults.length > 0) {
-        sarifLog.runs[0].results = sarifResults;
+    // Per the SARIF spec §3.14.23, run.results must be present even if there are no results.
+    // This provides a positive indication that the run completed and no results were found.
+    sarifLog.runs[0].results = sarifResults;
```
Comment (michaelcfanning) [inline src/ESLint.Formatter/sarif.js]: it is acceptable for run.results to be null in cases where a catastrophic engine error prevented analysis from occurring. are you permitting this case?

e.g., if a user passes a single syntactically invalid file to analyze, run.results may be null (in cases where a scanner cannot function against syntactically incorrect code).

File: src/ESLint.Formatter/sarif.js [hunk 4]
```diff
@@ -54,13 +54,20 @@ module.exports = function (results, data) {
...
     const sarifRules = {};
     const sarifRuleIndices = {};
-    var nextRuleIndex = 0;
+    let nextRuleIndex = 0;
     const sarifResults = [];
     const embedFileContents = process.env.SARIF_ESLINT_EMBED === "true";
 
+    // Emit a tool execution notification with this id if ESLint emits a message with
+    // no ruleId (which indicates an internal error in ESLint).
+    const internalErrorId = "ESL9999"
```
Comment (michaelcfanning) [inline src/ESLint.Formatter/sarif.js]: >ESL9999 [](start = 29, length = 7)

Suggest using ESL0999 for this. A poorly adopted convention with MS compilers is for the 1000 - 1999 range to be preserved for core compiler/language errors and everything beyond is for additional analysis. IDs below 1000 are reserved for internal engine issues.

File: src/ESLint.Formatter/sarif.js (hunk 3 above)
Comment (michaelcfanning) [reply src/ESLint.Formatter/sarif.js]: "If the tool started but failed to begin its analysis (for example, because its command line was invalid), then again results MAY be present, and if present SHALL be null."

---
In reply to: [385957192](https://github.com/microsoft/sarif-sdk/pull/1793#discussion_r385957192) [](ancestors = 385957192)

Comment (lgolding) [reply src/ESLint.Formatter/sarif.js]: As we discussed offline: the engine did not fail to begin its analysis; it can produce real results before (and after) hitting this problem.

---
In reply to: [385958991](https://github.com/microsoft/sarif-sdk/pull/1793#discussion_r385958991) [](ancestors = 385958991,385957192)

File: src/ESLint.Formatter/sarif.js (hunk 4 above)
Comment (lgolding) [reply src/ESLint.Formatter/sarif.js]: Fixed.

---
In reply to: [385957944](https://github.com/microsoft/sarif-sdk/pull/1793#discussion_r385957944) [](ancestors = 385957944)

File: src/ESLint.Formatter/sarif.js (hunk 2 above)
Comment (lgolding) [reply src/ESLint.Formatter/sarif.js]: I'm still researching the root cause, but it appears to be ESLint's parsing engine (specifically, a component called the "scope analyzer") choking on a construct like this:
```
import Example from 'example';
```
This is valid starting in ES 2015. You could argue that this is a configuration error because the ESLint user didn't set that option. But

1. I'm still investigating, and
2. Even if that turned out to be the case for this particular error, it's not clear how the SARIF generator could look at an ESLint message-without-a-ruleId and determine in general whether it's a tool failure or a configuration error.

I mean, maybe I can actually look at the message and, if I recognize the string as a known configuration issue, I can put it in the tool configuration notifications, otherwise in the tool execution notifications.

But it's still early in my research. Don't take any of what I just said too seriously yet.

This issue was reported in November 2015 in [[https://github.com/eslint/eslint/issues/4344](https://github.com/eslint/eslint/issues/4344)](https://github.com/eslint/eslint/issues/4344).


---
In reply to: [385956543](https://github.com/microsoft/sarif-sdk/pull/1793#discussion_r385956543) [](ancestors = 385956543)

Comment (lgolding) [reply src/ESLint.Formatter/sarif.js]: Per our discussion: we will record these as tool configuration notifications for now, and record the question of how to distinguish tool configuration notifications from tool execution notifications in [https://github.com/Microsoft/sarif-sdk/issues/1798](https://github.com/Microsoft/sarif-sdk/issues/1798). @mikefan@microsoft.com FYI.

---
In reply to: [385975793](https://github.com/microsoft/sarif-sdk/pull/1793#discussion_r385975793) [](ancestors = 385975793,385956543)
