### PR TITLE
Fix #1629: Page command shouldn't throw on options error.

### LINKED ISSUE #1629: Multitool page command should return option errors without throwing
In the `page` command, if the user specifies invalid values for the `runIndex`, `index`, or `count` options, or the the input file path, it throws, and the user has to dig the useful information out of an exception dump. Just print the message to the console and return non-zero (as we now do for the call to `DriverUtilities.ReportWhetherOutputFileCanBeCreated`).

### PR DESCRIPTION
**Pull request by lgolding**
There's a big comment in PageCommandTests.cs that explains the rationale for the change (the comment is there because it's also the rationale for why I arranged the tests as I did), so I won't reproduce it here. See also the description of Issue #1629.

### CODE REVIEW

File: src/Sarif.Multitool/CommandBase.cs [hunk 1]
```diff
@@ -12,6 +13,24 @@ namespace Microsoft.CodeAnalysis.Sarif.Multitool
 {
     public abstract class CommandBase
     {
+        protected static bool ValidateNonNegativeCommandLineOption<T>(int optionValue, string optionName)
+        {
+            bool valid = true;
+
+            if (optionValue < 0)
+            {
+                string optionDescription = CommandUtilities.GetOptionDescription<T>(optionName);
```
Comment (lgolding) [inline src/Sarif.Multitool/CommandBase.cs]: >CommandUtilities [](start = 43, length = 16)

I have another PR out that moves this method into `DriverUtilities`, so whoever gets in second will have a small merge conflict to resolve.

File: src/Sarif.Multitool/PageCommand.cs [hunk 2]
```diff
@@ -40,22 +41,39 @@ public int Run(PageOptions options)
...
+            if (!ValidateOptions(options, _fileSystem)) { return 1; }
 
             // Load the JsonMap, if previously built and up-to-date, or rebuild it
             JsonMapNode root = LoadOrRebuildMap(options);
 
             // Write the desired page from the Sarif file
             ExtractPage(options, root);
 
-            return 1;
+            return 0;
```
Comment (lgolding) [inline src/Sarif.Multitool/PageCommand.cs]: >0 [](start = 19, length = 1)

This was just a bug :-)

File: src/Sarif.Multitool/PageOptions.cs [hunk 3]
```diff
@@ -50,7 +50,7 @@ internal class PageOptions
             "force",
             Default = true,
             HelpText = "Force overwrite of output file if it exists.")]
-        public bool Force { get; set; } = true;
```
Comment (lgolding) [inline src/Sarif.Multitool/PageOptions.cs]: This fixes #1630, "Multitool page command --force defaults to true and can't be changed."

Comment (lgolding) [inline src/Sarif.Multitool/PageOptions.cs]: There is a bug #1630, "Multitool page command --force defaults to true and can't be changed". This change does not fix that bug!

Rather, this change makes it easier to write my new unit tests in PageCommandTests. Without this change, I had to explicitly set `Force = false` in every one of my test cases except for the single case where `Force` needed to be `true`.

It makes sense to remove this initialization; I don't think there's a single other property in any of the options classes that's initialized like this. It also makes sense to fix #1630 by removing the `Default = true` on line 51, but I don't want to do that in this PR because it's a command line behavior change and I want to validate it with you first.

Note that with `Default = true`, not only do I think it's the wrong default, but there's no way to specify the value "false" on the command line! There's nothing like PowerShell's `-mySwitch:false` syntax to turn it off.

**Comment by lgolding** [comment]
@michaelcfanning is added to the review. #Closed

**Comment by lgolding** [comment]
@rtaket is added to the review. #Closed

**Comment by lgolding** [comment]
@harleenkohli is added to the review. #Closed

**Comment by lgolding** [comment]
@SurbhiMS is added to the review. #Closed

**Comment by lgolding** [comment]
@cfaucon is added to the review. #Closed
