### PR TITLE
Fix #1581 Handle null property value during deserialization

### LINKED ISSUE #1581: [PropertyBagConverter] Need improved handling of property with null value during deserialization
When trying to parse a SARIF string with a custom property that is null, a generic null reference exception is thrown that provides very limited information back tot he caller. Consider supporting null since support for null values in properties was added in #376. If not supported, then throw a more specific exception so that troubleshooting can be done by the consumer. The preferred fix for me in this case was to add logic to not add the property that had a null value. That may not be the case for others though. It took a lot of trial and error to figure out the underlying cause. Maybe the addition of a helper method would be great as well. This is what I'm doing in our codebase:
private static void SetPropertyIfNotNullOrEmpty(Sarif.PropertyBagHolder owningObject, string propertyName, string propertyValue)
{
    if (!string.IsNullOrWhiteSpace(propertyValue))
    {
        owningObject.SetProperty(propertyName, propertyValue);
    }
}

Happens here:
SarifLog log = JsonConvert.DeserializeObject<SarifLog>(sarifString);

Happens because of the null for the custom property named "member":
"properties": {
    "module": "3",
    "type": "∂.3",
    "member": null
}

Generic exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Sarif.Readers.PropertyBagConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at 
…[Custom method]

### PR DESCRIPTION
**Pull request by mhuguet**
Address #1581 by adding GetProperty<T> support for null and handling null values for properties during deserialization using PropertyBagConverter.

### CODE REVIEW

File: src/Sarif/Core/PropertyBagHolder.cs [hunk 1]
```diff
@@ -99,7 +99,9 @@ public T GetProperty<T>(string propertyName)
                         propertyName));
             }
 
-            return JsonConvert.DeserializeObject<T>(Properties[propertyName].SerializedValue);
+            SerializedPropertyInfo propValue = Properties[propertyName];
+
+            return propValue == null ? default : JsonConvert.DeserializeObject<T>(propValue.SerializedValue);
```
Comment (lgolding) [inline src/Sarif/Core/PropertyBagHolder.cs]: >default [](start = 39, length = 7)

TIL about the `default` literal! Nice.

File: src/Sarif/Readers/PropertyBagConverter.cs [hunk 2]
```diff
@@ -70,7 +70,16 @@ public override void WriteJson(JsonWriter writer, object value, JsonSerializer s
...
-                writer.WriteRawValue(propertyDictionary[key].SerializedValue);
+                string valueToSerialize = propertyDictionary[key]?.SerializedValue;
+
+                if (valueToSerialize == null)
+                {
+                    writer.WriteNull();
+                }
+                else
+                {
+                    writer.WriteRawValue(propertyDictionary[key].SerializedValue ?? "null");
```
Comment (mhuguet) [inline src/Sarif/Readers/PropertyBagConverter.cs]: Wait, this isn't right. I don't need this. Sorry.

File: src/Test.UnitTests.Sarif/Readers/PropertyBagConverterTests.cs [hunk 3]
```diff
@@ -111,6 +111,18 @@ public void PropertyBagConverter_RoundTripsGuidPropertyWithoutBraces()
             _roundTrippedObject.GetProperty<Guid>("g").Should().Be(expectedGuid);
         }
 
+        [Fact]
+        [Trait(TestTraits.Bug, "1581")]
```
Comment (lgolding) [inline src/Test.UnitTests.Sarif/Readers/PropertyBagConverterTests.cs]: >[Trait(TestTraits.Bug, "1581")] [](start = 8, length = 31)

Thank you!

File: src/Sarif/Core/PropertyBagHolder.cs (hunk 1 above)
Comment (lgolding) [inline src/Sarif/Core/PropertyBagHolder.cs]: >default [](start = 39, length = 7)

This makes sense for reference types but not for object types. Given `{ "properties": { "a": null } }`, I expect `GetProperty<int>("a")` to throw rather than returning 0.

I suggest we fix this (and add another test) by modifying line 104 as follows:
```
if (propValue == null)
{
    if (typeof<T>.IsValueType)
    {
        throw new InvalidOperationException(
            string.Format(
                CultureInfo.CurrentCulture,
                SdkResources.PropertyOfValueTypeCannotBeNull,
                propertyName,
                typeof(T).FullName));
    }

    return null;
}
else
{
    return JsonConvert.DeserializeObject<T>(propValue.SerializedValue)
}
```

No doubt this could be shortened with `??` and or `? : ` and or a `throw` expression, but it's complicated enough that I think it's better spelled out in full.

Message string: "The property bag contains a property {0} with the value null. It cannot be converted to the value type {1}."

Comment (mhuguet) [reply src/Sarif/Core/PropertyBagHolder.cs]: Adjusted per recommendations and added a test for value types

File: src/Sarif/Core/PropertyBagHolder.cs [hunk 4]
```diff
@@ -99,7 +99,26 @@ public T GetProperty<T>(string propertyName)
...
+                {
+                    throw new InvalidOperationException(
+                        string.Format(
+                            CultureInfo.CurrentCulture,
+                            SdkResources.PropertyOfValueTypeCannotBeNull,
+                            propertyName,
+                            typeof(T).FullName));
+                }
+
+                // This will return null for reference types. Could not set null here b/c T could be a value type as well.
```
Comment (lgolding) [inline src/Sarif/Core/PropertyBagHolder.cs]: >well [](start = 117, length = 4)

LOL! This makes me happy, because I was sad when the `default` literal didn't appear in my proposed code :-)

File: src/Test.UnitTests.Sarif/Readers/PropertyBagConverterTests.cs [hunk 5]
```diff
@@ -111,6 +111,30 @@ public void PropertyBagConverter_RoundTripsGuidPropertyWithoutBraces()
...
+        public void PropertyBagConverter_RoundTripsNullValueForValueType()
+        {
+            _input = "{\"properties\":{\"a\":null}}";
+
+            PerformRoundTrip();
+
+            Assert.Throws<InvalidOperationException>(() => _inputObject.GetProperty<int>("a"));
+            Assert.Throws<InvalidOperationException>(() => _roundTrippedObject.GetProperty<int>("a"));
```
Comment (lgolding) [inline src/Test.UnitTests.Sarif/Readers/PropertyBagConverterTests.cs]: >Assert [](start = 12, length = 6)

For uniformity with the rest of our test code, please use FluentAssertions for this:
```
Action action = () => _inputObject.GetProperty<int>("a");
action.ShouldThrow<InvalidOperationException>();

action = () => _roundTrippedObject.GetProperty<int>("a");
action.ShouldThrow<InvalidOperationException>();
```

Comment (mhuguet) [reply src/Test.UnitTests.Sarif/Readers/PropertyBagConverterTests.cs]: As discussed, changed to action.Should().Throw<T>()
